export default {
    INSURANCE_LIST: require('./INSURANCE_LIST'),
    INSURANCE_PURCHASING_PROCESS: require('./INSURANCE_PURCHASING_PROCESS'),
    DIRECT_PAYMENT_PROCESS: require('./DIRECT_PAYMENT_PROCESS'),
};