import REGEX from './REGEX';
import {PAGE_ID, PAGE_ID_TO_ROUTE, ROUTE_TO_PAGE_ID} from './ROUTE';
import CAROUSEL_IMAGE from './CAROUSEL_IMAGE';

export {REGEX, PAGE_ID, PAGE_ID_TO_ROUTE, ROUTE_TO_PAGE_ID, CAROUSEL_IMAGE};