// 页面的 ID，目前设想用于识别当前所在页面。Value 必须从 0 开始且连续（考虑到以后可能的需求），值可以随意修改
export default {
    INSURANCE_COMPANY_INSURANCE_LIST: 0,
    INSURANCE_COMPANY_INSURANCE_PUBLICATION: 1,
    INSURANCE_COMPANY_DIRECT_PAYMENT_PROCESS: 2,
    INSURANCE_COMPANY_DIRECT_PAYMENT_DETAIL: 3,
    INSURANCE_COMPANY_INSURANCE_PURCHASING_PROCESS: 4,
    INSURANCE_COMPANY_INSURANCE_PURCHASING_DETAIL: 5,
    INSURANCE_COMPANY_PERSONAL_CENTER: 6,
    INSURANCE_COMPANY_INSURANCE_DETAIL: 7,
};